### ISSUE TITLE
Snapclarity - Remove any spanish checks from TranslationBot

### ISSUE THREAD

**Issue by briandspahn** [CanadianCommander/translationBot#7]
Snapclarity does not have any spanish users at this point, so checking for or updating spanish content is not valuable.
only remove spanish checks if the effort is low - otherwise no biggie

**Comment by CanadianCommander** [comment]
I've removed Spanish from Snap!

**Comment by briandspahn** [comment]
awesome sauce, thank you CdnCmdr!
