### ISSUE TITLE
Introduce file extension to exported csv file

### ISSUE THREAD

**Issue by briandspahn** [CanadianCommander/translationBot#8]
AC:
* Add .csv as specific file extension to translate bot file output from slack

**Comment by CanadianCommander** [comment]
File extension is now correctly `.csv`

**Comment by briandspahn** [comment]
Woo hoo amazing tyvm

Brian Spahn, B. Eng
Software Engineering Manager
(250) 580-0099 | ***@***.******@***.***>
www.cloudmd.ca/Kii<https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cloudmd.ca%2FKii&data=05%7C01%7Cbrian.spahn%40cloudpractice.ca%7Cdfdee30a7fd44e9ab84e08daf7d14b6f%7C5efdcbddb0524fe69a47ecd636e16062%7C0%7C0%7C638094775825640199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=aUHQoBup9qbk1XDM89DN3tYKN2U01QHaIPE%2B%2F5K1Nx8%3D&reserved=0>

[Graphical user interface, text  Description automatically generated]<https://can01.safelinks.protection.outlook.com/?url=http%3A%2F%2Fwww.cloudmd.ca%2Fkii&data=05%7C01%7Cbrian.spahn%40cloudpractice.ca%7Cdfdee30a7fd44e9ab84e08daf7d14b6f%7C5efdcbddb0524fe69a47ecd636e16062%7C0%7C0%7C638094775825640199%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=EtWjaHWsTtT8%2FsRg2SGRK0cYxSNX8AKXuMtjt0MalkM%3D&reserved=0>
EFAP | Telemedicine | Occupational Health | Absence Management

From: Benjamin Benetti ***@***.***>
Sent: Sunday, March 12, 2023 1:07 PM
To: CanadianCommander/translationBot ***@***.***>
Cc: Brian Spahn ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [CanadianCommander/translationBot] Introduce file extension to exported csv file (Issue #8)

You don't often get email from ***@***.******@***.***>. Learn why this is important<https://aka.ms/LearnAboutSenderIdentification>

File extension is now correctly .csv

-
Reply to this email directly, view it on GitHub<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FCanadianCommander%2FtranslationBot%2Fissues%2F8%23issuecomment-1465287751&data=05%7C01%7Cbrian.spahn%40cloudmd.ca%7C2b71dc4a29a44e989c9908db23355838%7C5efdcbddb0524fe69a47ecd636e16062%7C0%7C0%7C638142484241836072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=JtgcI4Nkn8mH4uxuVKYBatPdt%2BxzRAW%2FZGTHHbSKTRc%3D&reserved=0>, or unsubscribe<https://can01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FA5XXIO5GUIA4DSL3C2ERLQLW3Y3HLANCNFSM6AAAAAAVUNNXSM&data=05%7C01%7Cbrian.spahn%40cloudmd.ca%7C2b71dc4a29a44e989c9908db23355838%7C5efdcbddb0524fe69a47ecd636e16062%7C0%7C0%7C638142484241836072%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=SbilEvjZcdJ1YQylqeWJVCqD6Nja7MNDFey0BNLKpGw%3D&reserved=0>.
You are receiving this because you authored the thread.Message ID: ***@***.******@***.***>>

Disclaimer: This message and any document attached there to is intended only for the addressee and may contain privileged or confidential information. This message may not be distributed or quoted, nor may the information contained be copied or extracted without the approval of CloudMD Software & Services Inc. E-mails are susceptible to alteration. CloudMD Software & Services Inc. shall not be liable for the message if altered, changed, or falsified. If you have received this message in error, please notify us immediately so that we may correct our internal records. Please then delete this original message. Thank you.

Avertissement: Ce message ainsi que tout document qui y est joint est destin? uniquement au destinataire et peut contenir des informations privil?gi?es ou confidentielles. Ce message ne peut ?tre diffus? ou cit?, et les informations qu'il contient ne peuvent ?tre copi?es ou extraites sans l'accord de CloudMD Software & Services Inc. Les courriels sont susceptibles d'?tre modifi?s. CloudMD Software & Services Inc. ne peut ?tre tenu responsable du message s'il est alt?r?, modifi? ou falsifi?. Si vous avez re?u ce message par erreur, veuillez nous en informer imm?diatement afin que nous puissions corriger nos donn?es internes. Veuillez ensuite supprimer le message d'origine. Merci.
